---
title: "El rol del género en la identificación de la sociosexualidad a partir de las voces"
author:
  - Maria Camila Wilches Restrepo:
      institute:
        - ueb
      equal_contributor: "yes"
      correspondence: "yes"
      email: mwilchesr@unbosque.edu.co 
  - Johan Sebastian Castiblanco Contreras:
      institute:
        - ueb
      equal_contributor: "yes"
      correspondence: "yes"
      email: jscastiblanco@unbosque.edu.co
institute:
  - ueb: Facultad de Psicología, Universidad El Bosque, Bogotá, 110121, Colombia.
header-includes: 
  \usepackage{setspace}
  \usepackage{float} 
  \floatplacement{figure}{H}
  \usepackage[utf8]{inputenc}
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \lhead{Trabajo de Grado}
  \rhead{\textit{Identificación de la sociosexualidad a partir de las voces}}
  \usepackage[spanish]{babel}
  \usepackage{hanging}
  \usepackage{orcidlink}
  \usepackage{tabularx}
date: "`r Sys.setlocale('LC_TIME');format(Sys.Date(),'%d %B, %Y')`"
output:
  bookdown::pdf_document2:
    highlight: zenburn
    number_sections: yes
    toc: no
    pandoc_args:
      - '--lua-filter=Files/scholarly-metadata.lua'
      - '--lua-filter=Files/author-info-blocks.lua'
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
bibliography: references.bib
urlcolor: blue
linkcolor: red
link-citations: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{=latex}
------------------------------------------------------\-\newline
\begin{tabularx}{\textwidth}{@{\enskip}>{\fontseries{b}\selectfont}l@{:\enskip}X@{}}
Supervisión & Juan David Leongómez \orcidlink{0000-0002-0092-6298} \newline 
\textit{EvoCo: Laboratorio de Evolución y Comportamiento Humano} \newline
Facultad de Psicología \newline
Universidad El Bosque \newline
Email: \href{mailto:jleongomez@unbosque.edu.co}{jleongomez@unbosque.edu.co}. Web: \href{https://jdleongomez.info/es}{jdleongomez.info} \\
\end{tabularx}

\begin{center}
\rule{\textwidth}{.4pt}
\end{center}

\begingroup
\leftskip2em
\rightskip\leftskip
\begin{center}
\textbf{\large{Resumen}}
\end{center}
\par
```
Acá debe ir el resumen del artículo. Por ahora, agregué algunas referencias de prueba, y configuré el documento para que las referencias sean APA7, esté en español, y los presente como autores en un formato mejor. También hice que todas los links estén en azul, y todas las referencias cruzadas (links a secciones dentro del artículo) estén en rojo. Todo lo podemos cambiar.

```{=latex}
\par
\endgroup
```
# Introducción

La sociosexualidad es la disposición que tienen los seres humanos para entablar relaciones sexuales casuales con múltiples personas, sin necesidad de un compromiso o de vínculos emocionales fuertes. Mientras que los individuos con una sociosexualidad restringida tienden a perseguir la monogamia, involucrarse de manera afectiva, formar lazos emocionales más fuertes y a tener relaciones de larga duración, personas con una sociosexualidad no restringida tienden a involucrarse en relaciones de pareja, que se caracterizan por exigir una menor inversión en tiempo, demostraciones de afecto o cariño, y por tener más relaciones sexuales sin compromiso así como múltiples parejas sexuales de corta duración [@simpson1992].

Simpson y Gangestad [-@simpson1991; -@simpson1992], sugieren que existe una fuerte relación entre las diferencias individuales, la sociosexualidad y la preferencia de pareja romántica. De hecho, la sociosexualidad juega un papel importante en la elección que tienen tanto hombres como mujeres, a la hora de relacionarse ya sea de manera afectiva o sexual con cualquier individuo; las diferencias de sexo que subyacen a la preferencia de pareja romántica, son producto del coste de apareamiento/competencia, versus el esfuerzo de la crianza y el compromiso basado en la monogamia [@gettler2019].

De acuerdo con @jones1998, la sociosexualidad y los diferentes tipos de motivaciones pueden jugar un papel importante a la hora de conformar y mantener una relación romántica, debido a que las bases motivacionales de cada individuo, se ven influenciadas por diferentes dimensiones de recompensa; en algunos casos, se presentan por motivaciones extrínsecas, las cuales están enfocadas en las recompensas sociales y relacionales; por otro lado se encuentran las motivaciones instrumentales, las cuales se caracterizan por obtener recompensas enfocadas en las recompensas interpersonales; por último, se encuentran las motivaciones intrínsecas, las cuales se enfocan en el valor que se tiene por la pareja y su relación. @jones1998 encontró que no existen diferencias significativas con respecto a las motivaciones extrínsecas entre individuos con una sociosexualidad más restringida e individuos con una sociosexualidad no restringida.

Por otra parte, se determinó que las personas con una sociosexualidad más restringida, poseen mayores motivaciones intrínsecas al involucrarse en relaciones románticas, mientras que con las personas con una sociosexualidad sin restricción, no se identificó si las motivaciones juegan un papel importante a la hora de elegir pareja. Por otro lado, es importante mencionar como la sociosexualidad influye en la percepción de la infidelidad y selección de pareja, se puede determinar que la sociosexualidad, tiene una relación estrecha con la infidelidad que puede existir en una relación de pareja, lo cual se puede presentar en ambos géneros; dentro de los resultados encontrados en el estudio de @treger2011, se pudo determinar que tanto en hombres como en mujeres, que tuvieron resultados de sociosexualidad más altos, tienden a ser más infieles y por tanto a tener relaciones más angustiosas (es decir, un miedo mucho mayor a que su pareja les sea infiel), así mismo, se puede afirmar que la sociosexualidad representa mejor la reacción de los hombres hacia una infidelidad, debido a la competencia intrasexual que hay dentro del mismo género, dando lugar a la probabilidad de que los hombres adopten y utilicen distintos mecanismos de carácter sexual para obtener una pareja femenina, en comparación con las mujeres, quienes no muestran una competencia intrasexual tan marcada, utilizando menos mecanismos sexuales para la elección de pareja [@treger2011].

Es importante dar hincapié a como la relación entre las hormonas y las características fenotipicas, juegan un papel importante a la hora de intentar obtener información sobre el sexo, estado de salud, vigor físico, relaciones de parentesco e incluso elaboración de juicios sobre los rasgos de personalidad de otro individuo, lo que tiene implicaciones en el origen de conductas sexuales como elección de pareja, en este caso, la testosterona es una de las principales hormonas sexual producidas por el cuerpo humano, que se relaciona con estas características y puede ser producida por medio de los órganos sexuales tanto masculinos como femeninos, como lo son los testículos, la placenta y los ovarios [@eisenegger2011]. Dentro de los estudios sobre la orientación sexual y la orientación sociosexual, han habido pocos estudios longitudinales sobre los cambios hormonales que pueden presentar los hombres con respecto a la sociosexualidad y el deseo sexual, esto se puede deber a que la testosterona, la cual es la hormona principal de los hombres, es muy variable y susceptible a cambios que son provocados por diferentes experiencias y/o parámetros sociales, sin embargo, según los hallazgos en el estudio de @stern2020 la actitud hacia el deseo en relaciones sexuales sin compromiso, fueron previstos por la interacción entre el cortisol y la testosterona. Asimismo, se encontró evidencia de que los hombres con niveles mas altos de testosterona, presentaban mucha mas aceptación y una actitud mas positiva hacia relaciones sexuales sin compromiso, sin embargo, esto se cumplía si tenían un nivel de cortisol con un promedio mas bajo [@stern2020]. Por otro lado, en el estudio de @marcinkowska2021, sugieren que la motivación sexual de las mujeres, puede estar influenciada por los cambios hormonales que se pueden producir durante el ciclo ovulatorio, en el cual se presentan concentraciones de hormonas sexuales como lo son el estradiol, la progesterona y la testosterona.

Es importante mencionar, las diferencias que pueden esperarse en la detección de la sociosexualidad por medio de las voces, estas pueden presentarse debido a las diferencias biológicas, principalmente por las estructuras vocales tanto en hombres como en mujeres, una de estas diferencias significativas es la frecuencia vibratoria de las cuerdas vocales, en los hombres por ejemplo, la testosterona influye sobre sus cuerdas vocales, en las que se puede evidenciar un engrosamiento de las mismas, dando lugar a que, en comparación con las mujeres, los hombres tengan un 60% mas de cuerdas vocales y una frecuencia fundamental con desviaciones más bajas [@aung2019]. Así mismo en el estudio de @valentova2019, se pudo concluir que el peso corporal influye sobre el atractivo percibido de los hombres tanto en el habla como en el canto, mientras que en las mujeres este no es un predictor significativo en cuestión del atractivo del canto, del mismo modo, en las mujeres aunque una frecuencia fundamental más alta predice el atractivo tanto en el habla como en el canto, en los hombres solo la frecuencia fundamental baja se relaciono con más atractivo en cuestiones del habla. Igualmente, en otro estudio de @stern2021, se evidencio que la voz puede dar varias pistas sobre la personalidad de los individuos y útil para inferir el sexo de los individuos, por lo cual, muchas veces los hombres con un tono de voz alto, son evaluados de manera distinta que las mujeres, aunque tengan un tono de voz semejante.

Es importante recalcar, la voz y varios parámetros vocales, los cuales son indicadores de una calidad alta de pareja en los cuales ciertas características vocales dan señales de las características de un individuo en cuestión de atractivo, salud, oportunidades de reproducción y estatus social [@pisanski2018]. Por lo tanto, la detección de la sociosexualidad se puede ver afectada por distintos estímulos, los cuales se utilizan como información variada para detectar la orientación sociosexual de una persona, sin embargo, muchos de estos estímulos no se relacionan directamente con la sociosexualidad, dando lugar a una falsa percepción, esto se evidencia en el estudio de @stillman2009, en las evaluaciones que se hacen a individuos femeninos y masculinos sobre la sociosexualidad femenina, donde se juzgaba la sonrisa, como se sentaban, si tenían una apariencia física más atractiva y si vestían de una manera más llamativa, esto daba como resultado que los jueces percibieran que estas mujeres eran mucho más sociosexuales de lo que en realidad eran en el auto informe donde se reflejaban resultados totalmente distintos.

# Método

Es importante destacar el inventario de orientación sociosexual (SOI), el cual se encarga de evaluar la sociosexualidad en una sola dimensión, con puntajes altos los cuales indican una tendencia de sexualidad más promiscua y/o con menos restricciones; así como, puntajes bajos los cuales reflejan una clara tendencia a una orientación sociosexual más restringida [@penke2008].

# Población y muestra

## Materiales

# Referencias
